//go:build ignore

// This tool dumps the magic bitboard tables to a Go file with hardcoded constants.
// Run: go run cmd/gen-magic/main.go
package main

import (
	"fmt"
	"os"

	"webassemble/pkg/engine"
)

func main() {
	// The init() functions in engine have already populated the tables.
	// We just need to dump them.

	f, err := os.Create("pkg/engine/magic_data.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by: go run cmd/gen-magic/main.go")
	fmt.Fprintln(f, "// DO NOT EDIT — regenerate only if the magic search algorithm changes.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "package engine")
	fmt.Fprintln(f, "")

	// Dump rook masks, magics, shifts, offsets, and attack table.
	fmt.Fprintln(f, "var rookMaskData = [64]Bitboard{")
	for sq := 0; sq < 64; sq++ {
		fmt.Fprintf(f, "\t0x%016x,\n", uint64(engine.RookMaskForDump(sq)))
	}
	fmt.Fprintln(f, "}")

	fmt.Fprintln(f, "var rookMagicData = [64]uint64{")
	for sq := 0; sq < 64; sq++ {
		fmt.Fprintf(f, "\t0x%016x,\n", engine.RookMagicForDump(sq))
	}
	fmt.Fprintln(f, "}")

	fmt.Fprintln(f, "var rookShiftData = [64]uint8{")
	for sq := 0; sq < 64; sq++ {
		fmt.Fprintf(f, "\t%d,\n", engine.RookShiftForDump(sq))
	}
	fmt.Fprintln(f, "}")

	fmt.Fprintln(f, "var rookOffsetTable = []Bitboard{")
	for _, bb := range engine.RookAttacksTableForDump() {
		fmt.Fprintf(f, "\t0x%016x,\n", uint64(bb))
	}
	fmt.Fprintln(f, "}")

	fmt.Fprintln(f, "var rookOffsetIndex = [64]int{")
	for sq := 0; sq < 64; sq++ {
		fmt.Fprintf(f, "\t%d,\n", engine.RookOffsetForDump(sq))
	}
	fmt.Fprintln(f, "}")

	// Bishop
	fmt.Fprintln(f, "var bishopMaskData = [64]Bitboard{")
	for sq := 0; sq < 64; sq++ {
		fmt.Fprintf(f, "\t0x%016x,\n", uint64(engine.BishopMaskForDump(sq)))
	}
	fmt.Fprintln(f, "}")

	fmt.Fprintln(f, "var bishopMagicData = [64]uint64{")
	for sq := 0; sq < 64; sq++ {
		fmt.Fprintf(f, "\t0x%016x,\n", engine.BishopMagicForDump(sq))
	}
	fmt.Fprintln(f, "}")

	fmt.Fprintln(f, "var bishopShiftData = [64]uint8{")
	for sq := 0; sq < 64; sq++ {
		fmt.Fprintf(f, "\t%d,\n", engine.BishopShiftForDump(sq))
	}
	fmt.Fprintln(f, "}")

	fmt.Fprintln(f, "var bishopOffsetTable = []Bitboard{")
	for _, bb := range engine.BishopAttacksTableForDump() {
		fmt.Fprintf(f, "\t0x%016x,\n", uint64(bb))
	}
	fmt.Fprintln(f, "}")

	fmt.Fprintln(f, "var bishopOffsetIndex = [64]int{")
	for sq := 0; sq < 64; sq++ {
		fmt.Fprintf(f, "\t%d,\n", engine.BishopOffsetForDump(sq))
	}
	fmt.Fprintln(f, "}")

	fmt.Fprintln(f)
	fmt.Println("Generated magic_data.go")
}